using System;
using System.Collections.Generic;
using System.Text;

namespace loki_bms_common.Database
{
    public enum DataSourceDropControl
    {
        DoNothing,
        CommandDrop,
        InstantDrop,
    }

    public enum FriendFoeStatus
    {
        KnownFriend,
        AssumedFriend,
        Neutral,
        Suspect,
        Hostile,
        Unknown,
        Pending,
    }

    public enum TrackType
    {
        Sim = 0,
        Internal = 1,
        External = 2,
        PPLI = 3,
    }

    public enum TrackCategory
    {
        None,
        Air,
        Ground,
        Ship,
    }

    /// <summary>
    /// The live/drop/etc status of a <see cref="TrackFile"/>
    /// </summary>
    public enum TrackStatus
    {
        /// <summary>
        /// This track has lost data and will be dropped if data is not restored. This happened automatically, without user input.
        /// </summary>
        Drop_Auto = 0,
        /// <summary>
        /// This track has received data recently and won't drop unless data is lost. This is the normal mode.
        /// </summary>
        Live = 1,
        /// <summary>
        /// This track has been manually commanded to drop and will be dropped soon, regardless of data freshness.
        /// </summary>
        Drop_Manual = 2,
        /// <summary>
        /// This track has been manually protected against dropping, and won't be destroyed if data is lost.<br/>
        /// Another call to Protect() will return this track to normal Live status
        /// </summary>
        Protected = 3,
        /// <summary>
        /// This track is generated by a replay system.
        /// </summary>
        Generated = 4,
    }

    [Flags]
    public enum IFFType
    {
        None = 0,
        Mode1 = 1,
        Mode2 = 2,
        Mode3 = 4,
        Mode4 = 8,
        TADIL = 16,
    }

    public enum TEType
    {
        None,
        SAM,
        Airbase,
        Markpoint,
        Waypoint,
        Bullseye,
        DefendedPoint,
        DownedAircraft,
        Other,
    }
}
